// <auto-generated />
using System;
using CalenderApp.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalenderApp.Persistence.Migrations
{
    [DbContext(typeof(CalenderAppDbContext))]
    [Migration("20240514111846_mig_01")]
    partial class mig_01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActivityCalender.Entities.Etkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OlusturanKullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TekrarDurumu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("Etkinliks");
                });

            modelBuilder.Entity("ActivityCalender.Entities.Kullanici", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KullaniciSifresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicis");
                });

            modelBuilder.Entity("ActivityCalender.Entities.KullaniciEtkinlik", b =>
                {
                    b.Property<string>("KullaniciId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EtkinlikId")
                        .HasColumnType("int");

                    b.HasKey("KullaniciId", "EtkinlikId");

                    b.HasIndex("EtkinlikId");

                    b.ToTable("KullaniciEtkinliks");
                });

            modelBuilder.Entity("ActivityCalender.Entities.Etkinlik", b =>
                {
                    b.HasOne("ActivityCalender.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany("OlusturduguEtkinlikler")
                        .HasForeignKey("OlusturanKullaniciId")
                        .IsRequired();

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("ActivityCalender.Entities.KullaniciEtkinlik", b =>
                {
                    b.HasOne("ActivityCalender.Entities.Etkinlik", "Etkinlik")
                        .WithMany("KatilanKullanicilar")
                        .HasForeignKey("EtkinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ActivityCalender.Entities.Kullanici", "Kullanici")
                        .WithMany("KatildigiEtkinlikler")
                        .HasForeignKey("KullaniciId")
                        .IsRequired();

                    b.Navigation("Etkinlik");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("ActivityCalender.Entities.Etkinlik", b =>
                {
                    b.Navigation("KatilanKullanicilar");
                });

            modelBuilder.Entity("ActivityCalender.Entities.Kullanici", b =>
                {
                    b.Navigation("KatildigiEtkinlikler");

                    b.Navigation("OlusturduguEtkinlikler");
                });
#pragma warning restore 612, 618
        }
    }
}
